apiVersion: v1
kind: Template
metadata:
  name: sources
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: sources
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: superkey-worker
      minReplicas: ${{MIN_REPLICAS}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: DISABLE_RESOURCE_CREATION
          value: ${DISABLE_RESOURCE_CREATION}
        - name: DISABLE_RESOURCE_DELETION
          value: ${DISABLE_RESOURCE_DELETION}
        - name: SOURCES_SCHEME
          value: ${SOURCES_SCHEME}
        - name: SOURCES_HOST
          value: ${SOURCES_HOST}
        - name: SOURCES_PORT
          value: ${SOURCES_PORT}        
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
    kafkaTopics:
    - topicName: platform.sources.superkey-requests
      partitions: 3
      replicas: 3
parameters:
- name: CPU_LIMIT
  value: "100m"
- name: CPU_REQUEST
  value: "50m"
- name: DISABLE_RESOURCE_CREATION
  value: "false"
- name: DISABLE_RESOURCE_DELETION
  value: "false"
- description: Image
  name: IMAGE
  value: quay.io/cloudservices/sources-superkey-worker
- name: IMAGE_TAG
  value: latest   
- name: LOG_LEVEL
  value: WARN    
- name: MEMORY_LIMIT
  value: "50Mi"
- name: MEMORY_REQUEST
  value: "25Mi"  
- name: MIN_REPLICAS
  description: The number of replicas to use for the prometheus deployment
  value: "1"                               
- name: SOURCES_SCHEME
  displayName: Sources Service Scheme
  description: Scheme to use for the Sources service URL.
  value: http
- name: SOURCES_HOST
  displayName: Sources Service Host
  description: Host to use for the Sources service URL.
  value: sources-api
- name: SOURCES_PORT
  displayName: Sources Service Port
  description: Port to use for the Sources service URL.
  value: "8000"
